version: '3.7'

services:

  redis:
    image: redis
    ports:
      - 6379:6379

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['celery', '-A', 'crawler.app', 'worker', '-l', 'info', '--queues', 'crawler,extract']
    environment:
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - 5557:5555
    depends_on:
      - redis
